PROGRAM SUMAR ( INPUT, OUTPUT );
  {
    SUMA LA CANTIDAD DE NUMEROS QUE SE INDICA CUANDO
    SE EJECUTA EL PROGRAMA Y SE PIDE UN VALOR 
    PARA LA VARIABLE LLAMADA CUANTOS
  }

(* INDICA QUE VA A USAR LA UNIDAD O LIBRERIA DE PANTALLA *)
USES
  CRT;

VAR
  CONTADOR: INTEGER;
  CUANTOS:  INTEGER;
  NUMERO:   REAL;
  SUMA:     REAL;
  TECLA: CHAR;

(* INICIO DEL PROGRAMA SUMAR *)

BEGIN
  CLRSCR; { LIMPIA LA PANTALLA }
  
  { ENTRADA DE DATOS }

  TEXTCOLOR( YELLOW );           { COLOR AMARILLO }
  TEXTBACKGROUND( RED );         { FONDO ROJO }
  GOTOXY( 20, 5 );               { VAMOS A UNA POSICION DE LA PANTALLA }

  WRITELN ( OUTPUT, 'INDIQUE LA CANTIDAD DE NUMEROS A SUMAR:' );
  DELAY( 1000 );  (* HACE UNA PAUSA *)
  READLN ( CUANTOS );
  WRITELN;  
  WRITELN ( OUTPUT );  
  TEXTCOLOR( WHITE );           { COLOR BLANCO }
  TEXTBACKGROUND( BLACK);         { FONDO NEGRO }  

  (* INICIALIZACIÓN DE VARIABLES 
     QUE NECESITA EL PROGRAMA PARA REALIZAR SUS CALCULOS *)

  CONTADOR := 0;
  SUMA     := 0.0;

  { INICIO DEL CICLO }

  SOUND( 220 ); { SONIDO DE FRECUENCIA 220 HZ }
  WRITELN ( OUTPUT );
  WRITELN ( 'SUMANDO...' );
  WRITELN;

  REPEAT
    WRITELN ( OUTPUT, 'INDIQUE EL NUMERO A SUMAR:' );
    READLN ( NUMERO );
    SUMA     := SUMA + NUMERO;
    CONTADOR := CONTADOR + 1
  UNTIL CONTADOR >= CUANTOS;

  TEXTBACKGROUND ( BLUE );       { CON FONDO AZUL }
  WRITELN;
  WRITELN ( OUTPUT );
  WRITELN ( OUTPUT, 'SUMA DE LOS NUMEROS; PULSE UNA TECLA PARA TERMINAR:' );
  WRITELN ( SUMA: 7:2 );
  TECLA := READKEY;              { ESPERAMOS QUE SE PULSE UNA TECLA }
  WRITELN ( OUTPUT, 'ADIOS :-)' );
  DELAY( 2000 );                 { PAUSA ANTES DE ACABAR }
  TEXTCOLOR( LIGHTGRAY );        { COLORES POR DEFECTO DEL CMD/DOS }
  TEXTBACKGROUND( BLACK );       { Y BORRAMOS LA PANTALLA }
  CLRSCR
END .

(* FIN DEL PROGRAMA SUMAR *)
